/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as McpConnectionIdRouteImport } from './routes/mcp/$connectionId'
import { Route as OauthSplatRouteImport } from './routes/oauth/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConnectionsConnectionIdRouteImport } from './routes/api/connections/$connectionId'
import { Route as ApiConnectionsConnectionIdAuthorizeRouteImport } from './routes/api/connections/$connectionId/authorize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConnectionIdRoute = McpConnectionIdRouteImport.update({
  id: '/mcp/$connectionId',
  path: '/mcp/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSplatRoute = OauthSplatRouteImport.update({
  id: '/oauth/$',
  path: '/oauth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsConnectionIdRoute =
  ApiConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => ApiConnectionsRoute,
  } as any)
const ApiConnectionsConnectionIdAuthorizeRoute =
  ApiConnectionsConnectionIdAuthorizeRouteImport.update({
    id: '/authorize',
    path: '/authorize',
    getParentRoute: () => ApiConnectionsConnectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/mcp/$connectionId': typeof McpConnectionIdRoute
  '/oauth/$': typeof OauthSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connections/$connectionId': typeof ApiConnectionsConnectionIdRouteWithChildren
  '/api/connections/$connectionId/authorize': typeof ApiConnectionsConnectionIdAuthorizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/mcp/$connectionId': typeof McpConnectionIdRoute
  '/oauth/$': typeof OauthSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connections/$connectionId': typeof ApiConnectionsConnectionIdRouteWithChildren
  '/api/connections/$connectionId/authorize': typeof ApiConnectionsConnectionIdAuthorizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/mcp/$connectionId': typeof McpConnectionIdRoute
  '/oauth/$': typeof OauthSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connections/$connectionId': typeof ApiConnectionsConnectionIdRouteWithChildren
  '/api/connections/$connectionId/authorize': typeof ApiConnectionsConnectionIdAuthorizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/connections'
    | '/mcp/$connectionId'
    | '/oauth/$'
    | '/api/auth/$'
    | '/api/connections/$connectionId'
    | '/api/connections/$connectionId/authorize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/connections'
    | '/mcp/$connectionId'
    | '/oauth/$'
    | '/api/auth/$'
    | '/api/connections/$connectionId'
    | '/api/connections/$connectionId/authorize'
  id:
    | '__root__'
    | '/'
    | '/api/connections'
    | '/mcp/$connectionId'
    | '/oauth/$'
    | '/api/auth/$'
    | '/api/connections/$connectionId'
    | '/api/connections/$connectionId/authorize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConnectionsRoute: typeof ApiConnectionsRouteWithChildren
  McpConnectionIdRoute: typeof McpConnectionIdRoute
  OauthSplatRoute: typeof OauthSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$connectionId': {
      id: '/mcp/$connectionId'
      path: '/mcp/$connectionId'
      fullPath: '/mcp/$connectionId'
      preLoaderRoute: typeof McpConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$': {
      id: '/oauth/$'
      path: '/oauth/$'
      fullPath: '/oauth/$'
      preLoaderRoute: typeof OauthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$connectionId': {
      id: '/api/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/api/connections/$connectionId'
      preLoaderRoute: typeof ApiConnectionsConnectionIdRouteImport
      parentRoute: typeof ApiConnectionsRoute
    }
    '/api/connections/$connectionId/authorize': {
      id: '/api/connections/$connectionId/authorize'
      path: '/authorize'
      fullPath: '/api/connections/$connectionId/authorize'
      preLoaderRoute: typeof ApiConnectionsConnectionIdAuthorizeRouteImport
      parentRoute: typeof ApiConnectionsConnectionIdRoute
    }
  }
}

interface ApiConnectionsConnectionIdRouteChildren {
  ApiConnectionsConnectionIdAuthorizeRoute: typeof ApiConnectionsConnectionIdAuthorizeRoute
}

const ApiConnectionsConnectionIdRouteChildren: ApiConnectionsConnectionIdRouteChildren =
  {
    ApiConnectionsConnectionIdAuthorizeRoute:
      ApiConnectionsConnectionIdAuthorizeRoute,
  }

const ApiConnectionsConnectionIdRouteWithChildren =
  ApiConnectionsConnectionIdRoute._addFileChildren(
    ApiConnectionsConnectionIdRouteChildren,
  )

interface ApiConnectionsRouteChildren {
  ApiConnectionsConnectionIdRoute: typeof ApiConnectionsConnectionIdRouteWithChildren
}

const ApiConnectionsRouteChildren: ApiConnectionsRouteChildren = {
  ApiConnectionsConnectionIdRoute: ApiConnectionsConnectionIdRouteWithChildren,
}

const ApiConnectionsRouteWithChildren = ApiConnectionsRoute._addFileChildren(
  ApiConnectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConnectionsRoute: ApiConnectionsRouteWithChildren,
  McpConnectionIdRoute: McpConnectionIdRoute,
  OauthSplatRoute: OauthSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
