/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as BrowseSplatRouteImport } from './routes/browse.$'
import { Route as GrantsIndexRouteImport } from './routes/grants.index'
import { Route as GrantsGrantIdRouteImport } from './routes/grants.$grantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSplatRoute = BrowseSplatRouteImport.update({
  id: '/browse/$',
  path: '/browse/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsIndexRoute = GrantsIndexRouteImport.update({
  id: '/grants/',
  path: '/grants/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsGrantIdRoute = GrantsGrantIdRouteImport.update({
  id: '/grants/$grantId',
  path: '/grants/$grantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorize': typeof AuthorizeRoute
  '/browse/$': typeof BrowseSplatRoute
  '/grants/$grantId': typeof GrantsGrantIdRoute
  '/grants/': typeof GrantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorize': typeof AuthorizeRoute
  '/browse/$': typeof BrowseSplatRoute
  '/grants/$grantId': typeof GrantsGrantIdRoute
  '/grants': typeof GrantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorize': typeof AuthorizeRoute
  '/browse/$': typeof BrowseSplatRoute
  '/grants/$grantId': typeof GrantsGrantIdRoute
  '/grants/': typeof GrantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/authorize'
    | '/browse/$'
    | '/grants/$grantId'
    | '/grants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/audit' | '/authorize' | '/browse/$' | '/grants/$grantId' | '/grants'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/authorize'
    | '/browse/$'
    | '/grants/$grantId'
    | '/grants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthorizeRoute: typeof AuthorizeRoute
  BrowseSplatRoute: typeof BrowseSplatRoute
  GrantsGrantIdRoute: typeof GrantsGrantIdRoute
  GrantsIndexRoute: typeof GrantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$': {
      id: '/browse/$'
      path: '/browse/$'
      fullPath: '/browse/$'
      preLoaderRoute: typeof BrowseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants/': {
      id: '/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof GrantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants/$grantId': {
      id: '/grants/$grantId'
      path: '/grants/$grantId'
      fullPath: '/grants/$grantId'
      preLoaderRoute: typeof GrantsGrantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthorizeRoute: AuthorizeRoute,
  BrowseSplatRoute: BrowseSplatRoute,
  GrantsGrantIdRoute: GrantsGrantIdRoute,
  GrantsIndexRoute: GrantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
